pool:
  name: Azure Pipelines
  demands: npm

steps:
  - task: Npm@1
    displayName: "npm install"
    inputs:
      verbose: false

  - task: Npm@1
    displayName: "npm build"
    inputs:
      command: custom
      verbose: false
      customCommand: "run build prod"

  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: dist
      includeRootFolder: false
